[package]
name = "rummy-nights"
version = "0.2.0"
description = "A rummy score counter web app written with Rust/Dioxus and Tailwind CSS."
repository = "https://github.com/arqalite/rummy-nights"
readme = "README.md"
license = "MIT"
edition = "2021"
categories = ["games"]
keywords = ["rummy", "game", "counter", "score"]
publish = false
build = "src/build.rs"

[dependencies]
dioxus = {version = "0.2", features = ["web", "fermi"]}
gloo-storage = "0.2"
gloo-console = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
chrono = "0.4"
