[package]
name = "rummy-nights"
version = "0.1.0"
description = "A rummy score counter web app written with Rust/Dioxus and Tailwind CSS."
repository = "https://github.com/arqalite/rummy-nights"
readme = "README.md"
license = "MIT"
edition = "2021"
categories = ["games"]
keywords = ["rummy", "game", "counter", "score"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = {git = "https://github.com/dioxuslabs/dioxus.git"}
dioxus-web = {git = "https://github.com/dioxuslabs/dioxus.git"}
fermi = { git = "https://github.com/dioxuslabs/dioxus.git"}
gloo-storage = "0.2.2"
gloo-console = "0.2.3"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"