[package]
name = "rummy-nights"
version = "1.1.2"
description = "A rummy score counter web app written with Rust/Dioxus and Tailwind CSS."
repository = "https://github.com/arqalite/rummy-nights"
readme = "README.md"
license = "MIT"
edition = "2021"
categories = ["games"]
keywords = ["rummy", "game", "counter", "score"]
publish = false
build = "src/build.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[dependencies]
gloo-storage = "0.3"
gloo-console = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
phf = { version = "0.11", features = ["macros"] }
time = "0.3"
dioxus = { version = "0.6.3", features = [] }

[build-dependencies]
chrono = "0.4"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
