[build]
target = "index.html"
release = false
dist = "dist"
filehash = false
public_url = "/"

[serve]
open = false

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-o", "./style.css", "--minify"]