[build]
target = "index.html"
release = false
dist = "dist"
filehash = false
public_url = "/"

[serve]
# The address to serve on.
address = "127.0.0.2"
# The port to serve on.
port = 8080
open = false

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-o", "./style.css", "--minify"]