name: Deploy to Vercel - Production

on:
  push:
    tags:        
      - '*'
      
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download Tailwind
        uses: supplypike/setup-bin@v1
        with:
          uri: 'https://github.com/tailwindlabs/tailwindcss/releases/download/latest/tailwindcss-linux-x64'
          name: 'tailwindcss'
          version: 'latest'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install trunk
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: install
          args: trunk

      - name: Build web pages
        run: trunk build --release

      - name: Deploy to Vercel (prod)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}  # Required
          vercel-project-id: ${{ secrets.PROJECT_ID }} # Required 
          working-directory: ./dist

